### ISSUE TITLE
HDFS relating operations in runQuery should be parallel

### ISSUE THREAD

**Issue by joshuayao** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#20]
In early BB, these operations are partial parallel. So, it increases about 8~9s for each query with latest BB.

**Comment by Manuel-Danisch** [comment]
Hi,

as far as I remember, running these commands in background break all error handling. If you run "runCmdWithErrorCheck" in background, the "exit 1" in that method will most likely terminate the subshell instead of the bigBench script itself (bash tends to run everything in a subshell, as soon as things get more sophisticated...). Even if you change that code to something else (e.g., leave out runCmdWithErrorCheck) , you still have to check the return value of every background process right before the "wait". I don't know how this could be accomplished reliably in bash.

This problem was the reason why I changed these commands from background to foreground processes in the first place. If you can guarantee that error handling still works with your patch, I am happy to merge your changes. For the moment, I tend towards not merging your changes as I am certain that we might run into error handling problems.

Best regards,
Manuel

**Comment by Michael-Frank** [comment]
Update: New solution - install "snakebite" hdfs client on you gateway machine from which you run Big-Data-Benchmark-For-Big-Bench.
https://github.com/spotify/snakebite
You can activate snakebite (if installed) in: conf/userSettings.conf (end of file).
Its not used for everything, but the performance critical paths can use snakebite instead of hadoop fs enabled.

Parallel execution is not desired and not possible (e.g. you have to delete,recreate and then cmod a folder in that order).
The real underlying issue of this ticket is the painfull slowness of the "hadoop fs" or "hdfs/dfs" commands, where most time is spent starting up and not executing the command itself.
Using snakebite hdfs client, which is now supported, reduces this time significantly, shaving off 10-30 seconds of execution time from each query. This is most noticable and beneficial with small scalefactors or non MR execution engines like TEZ/SPARK.

**Comment by bdgowda1** [comment]
@joshuayao closing this for now, re-open if this is still an issue
