### ISSUE TITLE
q27 validation failed if the data scale is 1000

### ISSUE THREAD

**Issue by joshuayao** [intel-hadoop/Big-Data-Benchmark-for-Big-Bench#47]
We got the following exception in q27 validation results. Actually, the q27 result is correct.

[Exception]
/opt/Big-Data-Benchmark-for-Big-Bench-0.5/logs/q27_hive_power_test_0.log:137:Validation failed: Query did not return results
/opt/Big-Data-Benchmark-for-Big-Bench-0.5/logs/q27_hive_throughput_test_1_0.log:149:Validation failed: Query did not return results
/opt/Big-Data-Benchmark-for-Big-Bench-0.5/logs/q27_hive_throughput_test_1_1.log:138:Validation failed: Query did not return results

We also check the log and found the following issue:
[LOG]
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
cat: Unable to write to output stream.
Validation failed: Query did not return results.

I modified the validation script of q27 as follows, it passes.
hadoop fs -cat "$RESULT_DIR/*" | tail -n 10 | wc -l

**Comment by Manuel-Danisch** [comment]
Hi @joshuayao,

This seems odd. We also tested SF1000 on our test cluster, and the validation worked the way it is now. All other queries use head for validation as well and that also seems to work. Furthermore, using tail instead of head should not make any difference, exept that tail is much more inefficient (because for tail to work, the complete result has to be read, while head closes the stream after the first ten lines).

Could you please repeat the validation with the original code (head)? I guess that this might be a "hadoop-command-sometimes-works-sometimes-not" problem.

Best regards,

Manuel

**Comment by joshuayao** [comment]
Hi @Manuel-Danisch,

Thanks for your quick response. I tried the command several times. It seems a random issue. 
But the following message is still there but it does not affect the result.
cat: Unable to write to output stream.


Best Regards,
Yi
